=begin
#Coinbase Exchange REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'cgi'

module CoinbasePro
  class CoinbasePriceOracleApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Get signed prices
    # Get cryptographically signed prices ready to be posted on-chain using Compound's Open Oracle smart contract.
    # @param [Hash] opts the optional parameters
    # @return [ApiCoinbasePriceOracle]
    def exchange_restapi_get_coinbase_price_oracle(opts = {})
      data, _status_code, _headers = exchange_restapi_get_coinbase_price_oracle_with_http_info(opts)
      data
    end

    # Get signed prices
    # Get cryptographically signed prices ready to be posted on-chain using Compound&#39;s Open Oracle smart contract.
    # @param [Hash] opts the optional parameters
    # @return [Array<(ApiCoinbasePriceOracle, Integer, Hash)>] ApiCoinbasePriceOracle data, response status code and response headers
    def exchange_restapi_get_coinbase_price_oracle_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: CoinbasePriceOracleApi.exchange_restapi_get_coinbase_price_oracle ...'
      end
      # resource path
      local_var_path = '/oracle'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'ApiCoinbasePriceOracle'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKeyAuthKey', 'ApiKeyAuthPassphrase', 'ApiKeyAuthSign', 'ApiKeyAuthTimestamp']

      new_options = opts.merge(
        :operation => :"CoinbasePriceOracleApi.exchange_restapi_get_coinbase_price_oracle",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CoinbasePriceOracleApi#exchange_restapi_get_coinbase_price_oracle\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
