=begin
#Coinbase Exchange REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for CoinbasePro::AccountsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AccountsApi' do
  before do
    # run before each test
    @api_instance = CoinbasePro::AccountsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountsApi' do
    it 'should create an instance of AccountsApi' do
      expect(@api_instance).to be_instance_of(CoinbasePro::AccountsApi)
    end
  end

  # unit tests for exchange_restapi_get_account
  # Get a single account by id
  # Information for a single account. Use this endpoint when you know the account_id. API key must belong to the same profile as the account.
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @return [ApiAccount]
  describe 'exchange_restapi_get_account test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for exchange_restapi_get_account_holds
  # Get a single account&#39;s holds
  # List the holds of an account that belong to the same profile as the API key. Holds are placed on an account for any active orders or pending withdraw requests. As an order is filled, the hold amount is updated. If an order is canceled, any remaining hold is removed. For withdrawals, the hold is removed after it is completed.
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :before Used for pagination. Sets start cursor to &#x60;before&#x60; date.
  # @option opts [String] :after Used for pagination. Sets end cursor to &#x60;after&#x60; date.
  # @option opts [Integer] :limit Limit on number of results to return.
  # @return [Array<ApiAccountHold>]
  describe 'exchange_restapi_get_account_holds test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for exchange_restapi_get_account_ledger
  # Get a single account&#39;s ledger
  # Lists ledger activity for an account. This includes anything that would affect the accounts balance - transfers, trades, fees, etc.
  # @param account_id Returns list of ledger entries from this account id.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :start_date Filter results by minimum posted date.
  # @option opts [String] :end_date Filter results by maximum posted date.
  # @option opts [String] :before Used for pagination. Sets start cursor to &#x60;before&#x60; date.
  # @option opts [String] :after Used for pagination. Sets end cursor to &#x60;after&#x60; date.
  # @option opts [Integer] :limit Limit on number of results to return.
  # @option opts [String] :profile_id 
  # @return [Array<ApiAccountLedgerEntry>]
  describe 'exchange_restapi_get_account_ledger test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for exchange_restapi_get_account_transfers
  # Get a single account&#39;s transfers
  # Lists past withdrawals and deposits for an account.
  # @param account_id Returns list of transfers from this account id.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :before Used for pagination. Sets start cursor to &#x60;before&#x60; date.
  # @option opts [String] :after Used for pagination. Sets end cursor to &#x60;after&#x60; date.
  # @option opts [Integer] :limit Limit on number of results to return.
  # @option opts [String] :type 
  # @return [Array<ApiTransfer>]
  describe 'exchange_restapi_get_account_transfers test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for exchange_restapi_get_accounts
  # Get all accounts for a profile
  # Get a list of trading accounts from the profile of the API key.
  # @param [Hash] opts the optional parameters
  # @return [Array<ApiAccount>]
  describe 'exchange_restapi_get_accounts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
