=begin
#Coinbase Exchange REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for CoinbasePro::CoinbaseAccountsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CoinbaseAccountsApi' do
  before do
    # run before each test
    @api_instance = CoinbasePro::CoinbaseAccountsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CoinbaseAccountsApi' do
    it 'should create an instance of CoinbaseAccountsApi' do
      expect(@api_instance).to be_instance_of(CoinbasePro::CoinbaseAccountsApi)
    end
  end

  # unit tests for exchange_restapi_get_coinbase_accounts
  # Get all Coinbase wallets
  # Gets all the user&#39;s available Coinbase wallets (These are the wallets/accounts that are used for buying and selling on www.coinbase.com)
  # @param [Hash] opts the optional parameters
  # @return [Array<ApiCoinbaseAccount>]
  describe 'exchange_restapi_get_coinbase_accounts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for exchange_restapi_post_coinbase_account_addresses
  # Generate crypto address
  # Generates a one-time crypto address for depositing crypto.
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @return [ApiCoinbaseAccountGeneratedDepositAddress]
  describe 'exchange_restapi_post_coinbase_account_addresses test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
