=begin
#Coinbase Exchange REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for CoinbasePro::CoinbasePriceOracleApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CoinbasePriceOracleApi' do
  before do
    # run before each test
    @api_instance = CoinbasePro::CoinbasePriceOracleApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CoinbasePriceOracleApi' do
    it 'should create an instance of CoinbasePriceOracleApi' do
      expect(@api_instance).to be_instance_of(CoinbasePro::CoinbasePriceOracleApi)
    end
  end

  # unit tests for exchange_restapi_get_coinbase_price_oracle
  # Get signed prices
  # Get cryptographically signed prices ready to be posted on-chain using Compound&#39;s Open Oracle smart contract.
  # @param [Hash] opts the optional parameters
  # @return [ApiCoinbasePriceOracle]
  describe 'exchange_restapi_get_coinbase_price_oracle test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
