=begin
#Coinbase Exchange REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for CoinbasePro::CurrenciesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CurrenciesApi' do
  before do
    # run before each test
    @api_instance = CoinbasePro::CurrenciesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CurrenciesApi' do
    it 'should create an instance of CurrenciesApi' do
      expect(@api_instance).to be_instance_of(CoinbasePro::CurrenciesApi)
    end
  end

  # unit tests for exchange_restapi_get_currencies
  # Get all known currencies
  # Gets a list of all known currencies.  Note: Not all currencies may be currently in use for trading.
  # @param [Hash] opts the optional parameters
  # @return [Array<ApiCurrency>]
  describe 'exchange_restapi_get_currencies test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for exchange_restapi_get_currency
  # Get a currency
  # Gets a single currency by id.
  # @param currency_id 
  # @param [Hash] opts the optional parameters
  # @return [ApiCurrency]
  describe 'exchange_restapi_get_currency test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
