=begin
#Coinbase Exchange REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for CoinbasePro::FeesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FeesApi' do
  before do
    # run before each test
    @api_instance = CoinbasePro::FeesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FeesApi' do
    it 'should create an instance of FeesApi' do
      expect(@api_instance).to be_instance_of(CoinbasePro::FeesApi)
    end
  end

  # unit tests for exchange_restapi_get_fees
  # Get fees
  # Get fees rates and 30 days trailing volume.
  # @param [Hash] opts the optional parameters
  # @return [ApiFees]
  describe 'exchange_restapi_get_fees test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
