=begin
#Coinbase Exchange REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for CoinbasePro::TransfersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TransfersApi' do
  before do
    # run before each test
    @api_instance = CoinbasePro::TransfersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TransfersApi' do
    it 'should create an instance of TransfersApi' do
      expect(@api_instance).to be_instance_of(CoinbasePro::TransfersApi)
    end
  end

  # unit tests for exchange_restapi_get_payment_methods
  # Get all payment methods
  # Gets a list of the user&#39;s linked payment methods.
  # @param [Hash] opts the optional parameters
  # @return [Array<ApiPaymentMethod>]
  describe 'exchange_restapi_get_payment_methods test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for exchange_restapi_get_transfer
  # Get a single transfer
  # Get information on a single transfer.
  # @param transfer_id 
  # @param [Hash] opts the optional parameters
  # @return [ApiTransfer]
  describe 'exchange_restapi_get_transfer test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for exchange_restapi_get_transfers
  # Get all transfers
  # Gets a list of in-progress and completed transfers of funds in/out of any of the user&#39;s accounts.
  # @param [Hash] opts the optional parameters
  # @return [Array<ApiTransfer>]
  describe 'exchange_restapi_get_transfers test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for exchange_restapi_get_withdraw_fee_estimate
  # Get fee estimate for crypto withdrawal
  # Gets the fee estimate for the crypto withdrawal to crypto address
  # @param [Hash] opts the optional parameters
  # @option opts [String] :currency 
  # @option opts [String] :crypto_address 
  # @return [ApiFeeEstimateResult]
  describe 'exchange_restapi_get_withdraw_fee_estimate test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for exchange_restapi_post_deposit_coinbase_account
  # Deposit from Coinbase account
  # Deposits funds from a www.coinbase.com wallet to the specified &#x60;profile_id&#x60;.
  # @param api_post_transfer_coinbase_account_request 
  # @param [Hash] opts the optional parameters
  # @return [ApiTransferResult]
  describe 'exchange_restapi_post_deposit_coinbase_account test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for exchange_restapi_post_deposit_payment_method
  # Deposit from payment method
  # Deposits funds from a linked external payment method to the specified &#x60;profile_id&#x60;.
  # @param api_post_transfer_payment_method_request 
  # @param [Hash] opts the optional parameters
  # @return [ApiTransferResult]
  describe 'exchange_restapi_post_deposit_payment_method test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for exchange_restapi_post_withdraw_coinbase_account
  # Withdraw to Coinbase account
  # Withdraws funds from the specified &#x60;profile_id&#x60; to a www.coinbase.com wallet.
  # @param api_post_transfer_coinbase_account_request 
  # @param [Hash] opts the optional parameters
  # @return [ApiTransferResult]
  describe 'exchange_restapi_post_withdraw_coinbase_account test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for exchange_restapi_post_withdraw_crypto
  # Withdraw to crypto address
  # Withdraws funds from the specified &#x60;profile_id&#x60; to an external crypto address
  # @param api_post_transfer_crypto_request 
  # @param [Hash] opts the optional parameters
  # @return [ApiTransferResult]
  describe 'exchange_restapi_post_withdraw_crypto test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for exchange_restapi_post_withdraw_payment_method
  # Withdraw to payment method
  # Withdraws funds from the specified &#x60;profile_id&#x60; to a linked external payment method
  # @param api_post_transfer_payment_method_request 
  # @param [Hash] opts the optional parameters
  # @return [ApiTransferResult]
  describe 'exchange_restapi_post_withdraw_payment_method test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
