=begin
#Coinbase Exchange REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CoinbasePro::ApiUserExchangeTransferLimitsForCurrency
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe CoinbasePro::ApiUserExchangeTransferLimitsForCurrency do
  let(:instance) { CoinbasePro::ApiUserExchangeTransferLimitsForCurrency.new }

  describe 'test an instance of ApiUserExchangeTransferLimitsForCurrency' do
    it 'should create an instance of ApiUserExchangeTransferLimitsForCurrency' do
      expect(instance).to be_instance_of(CoinbasePro::ApiUserExchangeTransferLimitsForCurrency)
    end
  end
  describe 'test attribute "period_in_days"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "remaining"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "max"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
