=begin
#Coinbase Exchange REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CoinbasePro::ApiOrderSorting
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe CoinbasePro::ApiOrderSorting do
  let(:instance) { CoinbasePro::ApiOrderSorting.new }

  describe 'test an instance of ApiOrderSorting' do
    it 'should create an instance of ApiOrderSorting' do
      expect(instance).to be_instance_of(CoinbasePro::ApiOrderSorting)
    end
  end
end
