=begin
#Coinbase Exchange REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CoinbasePro::ApiCoinbaseAccountAddressWarning
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe CoinbasePro::ApiCoinbaseAccountAddressWarning do
  let(:instance) { CoinbasePro::ApiCoinbaseAccountAddressWarning.new }

  describe 'test an instance of ApiCoinbaseAccountAddressWarning' do
    it 'should create an instance of ApiCoinbaseAccountAddressWarning' do
      expect(instance).to be_instance_of(CoinbasePro::ApiCoinbaseAccountAddressWarning)
    end
  end
  describe 'test attribute "title"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "details"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "image_url"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
