=begin
#Coinbase Exchange REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CoinbasePro::ApiUserExchangeTransferLimits
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe CoinbasePro::ApiUserExchangeTransferLimits do
  let(:instance) { CoinbasePro::ApiUserExchangeTransferLimits.new }

  describe 'test an instance of ApiUserExchangeTransferLimits' do
    it 'should create an instance of ApiUserExchangeTransferLimits' do
      expect(instance).to be_instance_of(CoinbasePro::ApiUserExchangeTransferLimits)
    end
  end
  describe 'test attribute "transfer_limits"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "limit_currency"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
