=begin
#Coinbase Exchange REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CoinbasePro::ApiGetProfileResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe CoinbasePro::ApiGetProfileResponse do
  let(:instance) { CoinbasePro::ApiGetProfileResponse.new }

  describe 'test an instance of ApiGetProfileResponse' do
    it 'should create an instance of ApiGetProfileResponse' do
      expect(instance).to be_instance_of(CoinbasePro::ApiGetProfileResponse)
    end
  end
  describe 'test attribute "body"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
