=begin
#Coinbase Exchange REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CoinbasePro::ApiOrderStpFlag
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe CoinbasePro::ApiOrderStpFlag do
  let(:instance) { CoinbasePro::ApiOrderStpFlag.new }

  describe 'test an instance of ApiOrderStpFlag' do
    it 'should create an instance of ApiOrderStpFlag' do
      expect(instance).to be_instance_of(CoinbasePro::ApiOrderStpFlag)
    end
  end
end
