=begin
#Coinbase Exchange REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'date'
require 'time'

module CoinbasePro
  class ApiOrderStatus
    OPEN = "open".freeze
    PENDING = "pending".freeze
    REJECTED = "rejected".freeze
    DONE = "done".freeze
    ACTIVE = "active".freeze
    RECEIVED = "received".freeze
    ALL = "all".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ApiOrderStatus.constants.select { |c| ApiOrderStatus::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ApiOrderStatus" if constantValues.empty?
      value
    end
  end
end
