=begin
#Coinbase Exchange REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'date'
require 'time'

module CoinbasePro
  class ApiReportType
    FILLS = "fills".freeze
    ACCOUNT = "account".freeze
    OTC_FILLS = "otc_fills".freeze
    TYPE_1099K_TRANSACTION_HISTORY = "type_1099k_transaction_history".freeze
    TAX_INVOICE = "tax_invoice".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ApiReportType.constants.select { |c| ApiReportType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ApiReportType" if constantValues.empty?
      value
    end
  end
end
