=begin
#Coinbase Exchange REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'date'
require 'time'

module CoinbasePro
  class ApiAuctionBook
    attr_accessor :open_price

    attr_accessor :open_size

    attr_accessor :best_bid_price

    attr_accessor :best_bid_size

    attr_accessor :best_ask_price

    attr_accessor :best_ask_size

    attr_accessor :auction_state

    attr_accessor :can_open

    attr_accessor :time

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'open_price' => :'open_price',
        :'open_size' => :'open_size',
        :'best_bid_price' => :'best_bid_price',
        :'best_bid_size' => :'best_bid_size',
        :'best_ask_price' => :'best_ask_price',
        :'best_ask_size' => :'best_ask_size',
        :'auction_state' => :'auction_state',
        :'can_open' => :'can_open',
        :'time' => :'time'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'open_price' => :'String',
        :'open_size' => :'String',
        :'best_bid_price' => :'String',
        :'best_bid_size' => :'String',
        :'best_ask_price' => :'String',
        :'best_ask_size' => :'String',
        :'auction_state' => :'String',
        :'can_open' => :'String',
        :'time' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `CoinbasePro::ApiAuctionBook` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `CoinbasePro::ApiAuctionBook`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'open_price')
        self.open_price = attributes[:'open_price']
      end

      if attributes.key?(:'open_size')
        self.open_size = attributes[:'open_size']
      end

      if attributes.key?(:'best_bid_price')
        self.best_bid_price = attributes[:'best_bid_price']
      end

      if attributes.key?(:'best_bid_size')
        self.best_bid_size = attributes[:'best_bid_size']
      end

      if attributes.key?(:'best_ask_price')
        self.best_ask_price = attributes[:'best_ask_price']
      end

      if attributes.key?(:'best_ask_size')
        self.best_ask_size = attributes[:'best_ask_size']
      end

      if attributes.key?(:'auction_state')
        self.auction_state = attributes[:'auction_state']
      end

      if attributes.key?(:'can_open')
        self.can_open = attributes[:'can_open']
      end

      if attributes.key?(:'time')
        self.time = attributes[:'time']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @open_price.nil?
        invalid_properties.push('invalid value for "open_price", open_price cannot be nil.')
      end

      if @open_size.nil?
        invalid_properties.push('invalid value for "open_size", open_size cannot be nil.')
      end

      if @best_bid_price.nil?
        invalid_properties.push('invalid value for "best_bid_price", best_bid_price cannot be nil.')
      end

      if @best_bid_size.nil?
        invalid_properties.push('invalid value for "best_bid_size", best_bid_size cannot be nil.')
      end

      if @best_ask_price.nil?
        invalid_properties.push('invalid value for "best_ask_price", best_ask_price cannot be nil.')
      end

      if @best_ask_size.nil?
        invalid_properties.push('invalid value for "best_ask_size", best_ask_size cannot be nil.')
      end

      if @auction_state.nil?
        invalid_properties.push('invalid value for "auction_state", auction_state cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @open_price.nil?
      return false if @open_size.nil?
      return false if @best_bid_price.nil?
      return false if @best_bid_size.nil?
      return false if @best_ask_price.nil?
      return false if @best_ask_size.nil?
      return false if @auction_state.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          open_price == o.open_price &&
          open_size == o.open_size &&
          best_bid_price == o.best_bid_price &&
          best_bid_size == o.best_bid_size &&
          best_ask_price == o.best_ask_price &&
          best_ask_size == o.best_ask_size &&
          auction_state == o.auction_state &&
          can_open == o.can_open &&
          time == o.time
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [open_price, open_size, best_bid_price, best_bid_size, best_ask_price, best_ask_size, auction_state, can_open, time].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = CoinbasePro.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
