=begin
#Coinbase Exchange REST API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'date'
require 'time'

module CoinbasePro
  class ApiOrderCancelAfter
    MIN = "min".freeze
    HOUR = "hour".freeze
    DAY = "day".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ApiOrderCancelAfter.constants.select { |c| ApiOrderCancelAfter::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ApiOrderCancelAfter" if constantValues.empty?
      value
    end
  end
end
